name: fr3-recording
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy=1.26.0
  - pandas
  - pyyaml
  - tqdm
  - pip:
      - franky-control
      - pyrealsense2==2.58.2.10647
      - opencv-python==4.10.0.84
      - h5py
      - zarr
      - pyarrow
